#!/usr/bin/env python
"""
Train/fine-tune a NeMo ASR model for Mongolian using assets generated by
mn_finetune_setup.py.

Example (quick sanity run):
  .\\.speech_venv\\Scripts\\python.exe mn_finetune_train.py --dry-run

Example (real training):
  .\\.speech_venv\\Scripts\\python.exe mn_finetune_train.py ^
      --config mn_finetune_assets/starter_finetune_config.yaml ^
      --exp-dir mn_finetune_assets/experiments
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Dict

import lightning.pytorch as pl
from lightning.pytorch.callbacks import ModelCheckpoint
from lightning.pytorch.loggers import CSVLogger
from omegaconf import OmegaConf
import torch

import nemo.collections.asr as nemo_asr
from nemo.utils import logging as nemo_logging


if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Fine-tune NeMo ASR on Mongolian manifests/tokenizer.")
    p.add_argument("--config", type=Path, default=Path("mn_finetune_assets/starter_finetune_config.yaml"))
    p.add_argument("--exp-dir", type=Path, default=Path("mn_finetune_assets/experiments"))
    p.add_argument("--devices", type=int, default=1)
    p.add_argument("--num-workers", type=int, default=0)
    p.add_argument("--max-epochs", type=int, default=None)
    p.add_argument("--max-steps", type=int, default=None)
    p.add_argument(
        "--max-time",
        type=str,
        default=None,
        help="Maximum wall-clock training time for Lightning Trainer, e.g. '01:08:00:00' (DD:HH:MM:SS).",
    )
    p.add_argument("--train-batch-size", type=int, default=None)
    p.add_argument("--val-batch-size", type=int, default=None)
    p.add_argument("--learning-rate", type=float, default=None)
    p.add_argument("--precision", type=str, default=None)
    p.add_argument("--freeze-encoder", action="store_true")
    p.add_argument(
        "--nemo-log-level",
        type=str,
        default="WARNING",
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
    )
    p.add_argument("--dry-run", action="store_true", help="Run a tiny fit sanity-check (1-2 batches).")
    p.add_argument("--test-after-fit", action="store_true")
    p.add_argument("--resume-ckpt", type=str, default=None)
    p.add_argument("--save-nemo-path", type=Path, default=None)
    return p.parse_args()


def _must_exist(path: Path, label: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"{label} not found: {path}")


def ensure_vocab_txt(tokenizer_dir: Path) -> None:
    vocab_txt = tokenizer_dir / "vocab.txt"
    spm_vocab = tokenizer_dir / "tokenizer.vocab"
    if vocab_txt.exists():
        return
    if not spm_vocab.exists():
        raise FileNotFoundError(
            f"Missing tokenizer vocab files in {tokenizer_dir}. "
            f"Expected at least one of: {vocab_txt.name}, {spm_vocab.name}"
        )

    with spm_vocab.open("r", encoding="utf-8") as src, vocab_txt.open("w", encoding="utf-8") as dst:
        for line in src:
            line = line.strip()
            if not line:
                continue
            piece = line.split("\t", 1)[0]
            dst.write(piece + "\n")


def build_data_cfg(
    manifest: Path,
    sample_rate: int,
    batch_size: int,
    shuffle: bool,
    num_workers: int,
    pin_memory: bool,
) -> Dict[str, Any]:
    return {
        "manifest_filepath": str(manifest.resolve().as_posix()),
        "sample_rate": int(sample_rate),
        "batch_size": int(batch_size),
        "shuffle": bool(shuffle),
        "num_workers": int(num_workers),
        "pin_memory": bool(pin_memory),
        "is_tarred": False,
        "use_start_end_token": False,
    }


def freeze_encoder(model: torch.nn.Module) -> None:
    if not hasattr(model, "encoder"):
        return
    for p in model.encoder.parameters():
        p.requires_grad = False


def main() -> None:
    args = parse_args()
    _must_exist(args.config, "Config file")

    cfg = OmegaConf.load(args.config)

    base_model = str(cfg.base_model)
    tokenizer_dir = Path(str(cfg.tokenizer.dir))
    tokenizer_type = str(cfg.tokenizer.type)
    sample_rate = int(cfg.data.sample_rate)
    train_manifest = Path(str(cfg.data.train_manifest))
    val_manifest = Path(str(cfg.data.val_manifest))
    test_manifest = Path(str(cfg.data.test_manifest))

    _must_exist(tokenizer_dir, "Tokenizer dir")
    _must_exist(tokenizer_dir / "tokenizer.model", "tokenizer.model")
    ensure_vocab_txt(tokenizer_dir)
    _must_exist(train_manifest, "Train manifest")
    _must_exist(val_manifest, "Validation manifest")
    if args.test_after_fit:
        _must_exist(test_manifest, "Test manifest")

    train_bs = int(args.train_batch_size or cfg.data.train_batch_size)
    val_bs = int(args.val_batch_size or cfg.data.val_batch_size)
    max_epochs = int(args.max_epochs or cfg.training.max_epochs)
    lr = float(args.learning_rate or cfg.training.learning_rate)
    precision = str(args.precision or cfg.training.precision)
    seed = int(cfg.training.seed)

    use_gpu = torch.cuda.is_available()
    accelerator = "gpu" if use_gpu else "cpu"
    if not use_gpu and precision in {"16", "16-mixed", "bf16", "bf16-mixed"}:
        precision = "32"

    pl.seed_everything(seed, workers=True)
    if hasattr(nemo_logging, "set_verbosity"):
        nemo_logging.set_verbosity(getattr(nemo_logging, args.nemo_log_level))
    args.exp_dir.mkdir(parents=True, exist_ok=True)
    ckpt_dir = args.exp_dir / "checkpoints"
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    checkpoint_cb = ModelCheckpoint(
        dirpath=str(ckpt_dir),
        filename="epoch{epoch:02d}-step{step}",
        every_n_epochs=1,
        save_top_k=-1,
        save_last=True,
    )
    logger = CSVLogger(save_dir=str(args.exp_dir), name="logs")

    trainer_kwargs: Dict[str, Any] = dict(
        accelerator=accelerator,
        devices=args.devices,
        precision=precision,
        logger=logger,
        callbacks=[checkpoint_cb],
        default_root_dir=str(args.exp_dir),
        log_every_n_steps=10,
        max_epochs=max_epochs,
    )
    if args.max_steps is not None:
        trainer_kwargs["max_steps"] = int(args.max_steps)
    if args.max_time is not None:
        trainer_kwargs["max_time"] = args.max_time

    if args.dry_run:
        trainer_kwargs.update(
            fast_dev_run=False,
            max_epochs=1,
            max_steps=2,
            limit_train_batches=2,
            limit_val_batches=1,
            num_sanity_val_steps=0,
            log_every_n_steps=1,
        )

    trainer = pl.Trainer(**trainer_kwargs)

    print(f"Loading base model: {base_model}")
    model = nemo_asr.models.ASRModel.from_pretrained(model_name=base_model)
    model = model.to("cuda" if use_gpu else "cpu")
    model.train()
    model.set_trainer(trainer)

    print(f"Switching tokenizer to: {tokenizer_dir}")
    model.change_vocabulary(
        new_tokenizer_dir=str(tokenizer_dir.resolve()),
        new_tokenizer_type=tokenizer_type,
    )

    if args.freeze_encoder:
        print("Freezing encoder parameters.")
        freeze_encoder(model)

    pin_memory = use_gpu
    train_cfg = build_data_cfg(
        manifest=train_manifest,
        sample_rate=sample_rate,
        batch_size=train_bs,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=pin_memory,
    )
    val_cfg = build_data_cfg(
        manifest=val_manifest,
        sample_rate=sample_rate,
        batch_size=val_bs,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=pin_memory,
    )
    model.setup_training_data(train_cfg)
    model.setup_validation_data(val_cfg)

    if args.test_after_fit:
        test_cfg = build_data_cfg(
            manifest=test_manifest,
            sample_rate=sample_rate,
            batch_size=val_bs,
            shuffle=False,
            num_workers=args.num_workers,
            pin_memory=pin_memory,
        )
        if hasattr(model, "setup_test_data"):
            model.setup_test_data(test_cfg)

    optim_cfg = OmegaConf.create(
        {
            "name": "adamw",
            "lr": lr,
            "weight_decay": 1e-3,
        }
    )
    model.setup_optimization(optim_cfg)

    print("Starting fine-tuning...")
    trainer.fit(model, ckpt_path=args.resume_ckpt)

    if args.test_after_fit:
        print("Running test...")
        trainer.test(model)

    save_nemo = args.save_nemo_path or (args.exp_dir / "final_mn_finetuned.nemo")
    save_nemo.parent.mkdir(parents=True, exist_ok=True)
    model.save_to(str(save_nemo))
    print(f"Saved final .nemo model to: {save_nemo.resolve()}")


if __name__ == "__main__":
    main()
